linters:
  disable-all: true
  enable:
    - deadcode
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck
    - bodyclose
    - cyclop
    - dogsled
    - dupl
    - durationcheck
    - errname
    - errorlint
    - exportloopref
    - gocritic
    - goerr113
    - gosec
    - makezero
    - nilerr